
name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          # 要自行添加指定pnmp的版本信息，不能写 pnmp-version
          version: 8.6
          run_install: true


      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm


      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 使用ssh要生成github access token，然后在仓库的setting的actions里新建secret，值放入token。
          # 然后在这里自行添加指定的secret
          token: ${{ secrets.ACCESS_TOKEN }}
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: src/.vuepress/dist
